In [1]:
import torch
from torch.autograd import Variable
from model import Model, ConcatLayer

In [2]:
w = Variable(torch.Tensor([.8,.9,1.0,1.1,1.2]))
m = Model(w, 2, 2)
m.init_weight()

In [3]:
m.hidden_layers[0].linear.weight[0, 0] = 1.
print(m.grow())
d = m.to_dict()
m.state_dict()

True


OrderedDict([('hidden_layers.0.linear.weight',
              tensor([[ 1.0000, -0.0492],
                      [ 0.0724, -0.0121],
                      [ 0.0261,  0.0528],
                      [-0.0036,  0.0792],
                      [-0.0558, -0.0495],
                      [ 0.0450,  0.0109],
                      [ 0.0058,  0.0460]])),
             ('hidden_layers.0.activation.weight',
              tensor([[0.2591, 0.3188, 0.6246, 0.6451, 0.5813, 0.6187, 0.4974],
                      [0.8557, 0.6124, 0.0675, 0.1173, 0.1871, 0.4729, 0.8756],
                      [0.3562, 0.6442, 0.6288, 0.1405, 0.5791, 0.0233, 0.9349],
                      [0.2715, 0.3292, 0.4581, 0.7418, 0.5402, 0.6269, 0.0630]])),
             ('hidden_layers.1.linear.weight',
              tensor([[-0.0943,  0.0730,  0.0598, -0.0965, -0.0205,  0.0726, -0.0407,  0.0736,
                        0.0481],
                      [-0.0504,  0.0051,  0.0732,  0.0489,  0.0485,  0.0321,  0.0543,  0.0376,
            

In [4]:
w = Variable(torch.Tensor([.8,.9,1.0,1.1,1.2]))
m_loaded = Model.from_dict(w, 2, 2, d)
m_loaded.state_dict()

OrderedDict([('hidden_layers.0.linear.weight',
              tensor([[ 1.0000, -0.0492],
                      [ 0.0724, -0.0121],
                      [ 0.0261,  0.0528],
                      [-0.0036,  0.0792],
                      [-0.0558, -0.0495],
                      [ 0.0450,  0.0109],
                      [ 0.0058,  0.0460]])),
             ('hidden_layers.0.activation.weight',
              tensor([[0.2591, 0.3188, 0.6246, 0.6451, 0.5813, 0.6187, 0.4974],
                      [0.8557, 0.6124, 0.0675, 0.1173, 0.1871, 0.4729, 0.8756],
                      [0.3562, 0.6442, 0.6288, 0.1405, 0.5791, 0.0233, 0.9349],
                      [0.2715, 0.3292, 0.4581, 0.7418, 0.5402, 0.6269, 0.0630]])),
             ('hidden_layers.1.linear.weight',
              tensor([[-0.0943,  0.0730,  0.0598, -0.0965, -0.0205,  0.0726, -0.0407,  0.0736,
                        0.0481],
                      [-0.0504,  0.0051,  0.0732,  0.0489,  0.0485,  0.0321,  0.0543,  0.0376,
            

In [5]:
t = torch.ones(4, dtype=bool)
#i = torch.LongTensor([1,2])
i = 1
t[i] = False
t

tensor([ True, False,  True,  True])

In [13]:
layer = ConcatLayer(3,4,w)
layer.init_weight()
print(sum([p.numel() for p in layer.parameters()]))
list(layer.parameters())

28


[Parameter containing:
 tensor([[ 0.0518, -0.0449, -0.0404],
         [ 0.0086,  0.0208, -0.0663],
         [ 0.0549,  0.0157,  0.0115],
         [ 0.0715,  0.0939,  0.0920]], requires_grad=True),
 Parameter containing:
 tensor([[0.2013, 0.7283, 0.6067, 0.2790],
         [0.6726, 0.2672, 0.5264, 0.6256],
         [0.6079, 0.6144, 0.0492, 0.7283],
         [0.3708, 0.1443, 0.5937, 0.0175]], requires_grad=True)]

In [14]:
layer.append_nodes_out(2)
layer.append_nodes_in(3, 1)

In [15]:
layer

ConcatLayer(
  (linear): TertiaryLinear(in_features=4, out_features=6, bias=False)
  (activation): ActModule()
)

In [16]:
print(sum([p.numel() for p in layer.parameters()]))
list(layer.parameters())

48


[Parameter containing:
 tensor([[ 0.0518, -0.0449, -0.0404, -0.0079],
         [ 0.0086,  0.0208, -0.0663, -0.0514],
         [ 0.0549,  0.0157,  0.0115,  0.0530],
         [ 0.0715,  0.0939,  0.0920, -0.0291],
         [-0.0728, -0.0784, -0.0497,  0.0003],
         [-0.0592,  0.0458, -0.0463,  0.0681]], requires_grad=True),
 Parameter containing:
 tensor([[0.2013, 0.7283, 0.6067, 0.2790, 0.6727, 0.6997],
         [0.6726, 0.2672, 0.5264, 0.6256, 0.1988, 0.7959],
         [0.6079, 0.6144, 0.0492, 0.7283, 0.5251, 0.9297],
         [0.3708, 0.1443, 0.5937, 0.0175, 0.0192, 0.1354]], requires_grad=True)]

In [20]:
torch.Tensor([torch.Tensor([2])])

tensor([2.])

In [22]:
for i, s in reversed(list(enumerate(['a', 'b', 'c']))):
    print (i, s)

2 c
1 b
0 a
